name: Version

on: 
  workflow_dispatch:
    inputs:
      version-level:
        description: 'Version bump level major | minor | patch | premajor | preminor | prepatch | prerelease'     
        required: true
        default: 'preminor'
      version-preid:
        required: true
        description: 'Version preid'
        default: 'rc'
jobs:
  version:
    runs-on: ubuntu-latest
    env: 
      VERSION_LEVEL: ${{ github.event.inputs.version-level }}"
      VERSION_PREID: ${{ github.event.inputs.version-preid }}"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm ci
      - run: npm version -- ${{ env.VERSION_LEVEL }} --preid ${{ env.VERSION_PREID }}
      - run: npm build
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "chore(version): ${{ env.VERSION_LEVEL }}" 
          title: "chore(version): ${{ env.VERSION_LEVEL }}" 
          delete-branch: true
